version: "3.8"

services:
  api:
    build:
      context: .
    ports:
      - "7000:7000"
    environment:
      MONGODB_CONNECTION_STRING: mongodb+srv://kpaadarsh:dYpr9rAearIHYOvi@todo.zaxa2cs.mongodb.net/?retryWrites=true&w=majority
      JWT_SECREAT_KEY: gjsdhfkjsfda498784cbi#$$KJFkjjsjka$@%^&*()
    restart: always
